# I modified the github action from @arichornlover 's uYouEnhanced repo, but the original idea is by @ISnackable. Thanks to both of them!
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml

name: Build and Release YTMusicUltimate

on:
  workflow_dispatch:
    inputs: 
      decrypted_youtube_music_url:
        description: "https://www.dropbox.com/scl/fi/zog350g0mdmyed4selu5j/com.google.ios.youtubemusic-7.10-Decrypted.ipa?rlkey=htwx8454kashnaf11eowy5avy&st=25g477ss&dl=0"
        default: ""
        required: true
        type: string    
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTMusicUltimate
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.7
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make  

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/theos
          ref: 3da31488281ecf4394d10302d2629607f4a1aa07
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-16.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.7
        with:
          repository: qnblackcat/theos-jailed
          ref: master
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: YTMusicUltimate-v${{ github.run_number }}
          name: YTMusicUltimate-v${{ github.run_number }}
          files: main/packages/*.ipa
          draft: true
